features:
  - lat
  - lon
  - depth
  - temperature
  - pressure
  - sound_vel_direct
  - salinity
  - density
  - sv_mackenzie_residual
  - pressure_residual
  - pressure_depth_ratio
  - temp_gradient
  - spatial_z_dist
  - geo_out_of_bounds_dist

ordered_feature_names:
  - lat
  - lon
  - depth
  - temperature
  - pressure
  - sound_vel_direct
  - salinity
  - density
  - sv_mackenzie_residual
  - pressure_residual
  - pressure_depth_ratio
  - temp_gradient
  - spatial_z_dist
  - geo_out_of_bounds_dist
